// const col = {
//   bgWhite: "#fafafa",
//   bgGray: "#d4d4d4",
//   fgGray: "#888",
//   fgDarkGray: "#333",
//   fgBlack: "#222",
//   fgBlue: "#140191",
//   fgGreen: "#019114",
//   fgRed: "#910114",
//   black: "#000",
// };

// export default {
//   light: {
//     text: col.fgBlack,
//     textLight: col.fgGray,
//     background: col.bgWhite,
//     positive: col.fgGreen,
//     negative: col.fgRed,
//     highlight: col.fgBlue,
//     tabIconDefault: col.bgGray,
//     tabIconSelected: col.fgBlue,
//     dropShadow: col.fgGray,
//     boxOutline: col.fgBlack,
//     buttonSecondary: col.bgGray,
//   },
//   dark: {
//     text: col.bgWhite,
//     textLight: col.bgGray,
//     background: col.fgBlack,
//     positive: col.fgGreen,
//     negative: col.fgRed,
//     highlight: col.fgBlue,
//     tabIconDefault: col.fgGray,
//     tabIconSelected: col.bgWhite,
//     dropShadow: col.black,
//     boxOutline: col.bgGray,
//     buttonSecondary: col.fgDarkGray,
//   },
// };

// Using 400 palette of base 140191
const col = {
  light: "#f1f1f1",
  light2: "#f1f1f199",
  light3: "#f1f1f112",
  dark: "#121212",
  dark2: "#12121299",
  dark3: "#1212120D",
  // elevation: "#ffffff12",
  primary: "#4d6bbd",
  secondary: "#bb41bd",
  info: "#08abc6",
  success: "#b1d648",
  successLight: "#b1d64829",
  successAlt: "#8ca80e", // Using 700 in light mode
  danger: "#cc4736",
  dangerLight: "#cc473629",
};

export default {
  light: {
    text: col.dark,
    textLight: col.dark2,
    background: col.light,
    positive: col.successAlt,
    negative: col.danger,
    tabIconDefault: col.dark3,
    tabIconSelected: col.primary,
    dropShadow: col.dark2,
    boxOutline: col.dark2,
    boxFill: col.light,
    buttonPrimary: col.primary,
    buttonPrimaryContent: col.light,
    buttonSecondary: col.dark3,
    switchPositive: col.successLight,
    switchNegative: col.dangerLight,
  },
  dark: {
    text: col.light,
    textLight: col.light2,
    background: col.dark,
    positive: col.success,
    negative: col.danger,
    tabIconDefault: col.light2,
    tabIconSelected: col.light,
    dropShadow: "transparent",
    boxOutline: "transparent",
    boxFill: col.light3,
    buttonPrimary: col.primary,
    buttonPrimaryContent: col.light,
    buttonSecondary: col.light3,
    switchPositive: col.successLight,
    switchNegative: col.dangerLight,
  },
};
