// Using 400 palette of base 140191
const col = {
  light: "#f1f1f1",
  light2: "#f1f1f199",
  light3: "#f1f1f112",
  dark: "#121212",
  dark2: "#12121299",
  dark3: "#1212120D",
  primary: "#4d6bbd",
  secondary: "#bb41bd",
  info: "#08abc6",
  success: "#b1d648",
  successLight: "#b1d64829",
  successAlt: "#8ca80e", // Using 700 in light mode
  danger: "#cc4736",
  dangerLight: "#cc473629",
};

export default {
  light: {
    text: col.dark,
    textLight: col.dark2,
    background: col.light,
    positive: col.successAlt,
    negative: col.danger,
    tabIconDefault: col.dark3,
    tabIconSelected: col.primary,
    dropShadow: col.dark2,
    boxPositive: col.successLight,
    boxNegative: col.dangerLight,
    boxNeutral: col.dark3,
    boxOutlinePositive: col.successLight,
    boxOutlineNegative: col.dangerLight,
    boxOutlineNeutral: col.dark2,
    barOutline: col.dark2,
    buttonPrimary: col.primary,
    buttonPrimaryContent: col.light,
    buttonSecondary: col.dark3,
    switchPositive: col.successLight,
    switchNegative: col.dangerLight,
  },
  dark: {
    text: col.light,
    textLight: col.light2,
    background: col.dark,
    positive: col.success,
    negative: col.danger,
    tabIconDefault: col.light2,
    tabIconSelected: col.light,
    dropShadow: "transparent",
    boxPositive: col.successLight,
    boxNegative: col.dangerLight,
    boxNeutral: col.light3,
    boxOutlinePositive: "transparent",
    boxOutlineNegative: "transparent",
    boxOutlineNeutral: "transparent",
    barOutline: col.dark,
    buttonPrimary: col.primary,
    buttonPrimaryContent: col.light,
    buttonSecondary: col.light3,
    switchPositive: col.successLight,
    switchNegative: col.dangerLight,
  },
};
